<div class="container text-white" ng-init="carregarPessoa({{ $this->id }})">
    <h4>REST API - Contatos - @{{ pessoa.nome }}</h4>
    <a href="../" class="btn btn-sm btn-secondary my-3 me-2">
        <i class="fas fa-chevron-left me-2"></i>
        Voltar
    </a>
    <a href="" class="btn btn-sm btn-success my-3" data-bs-toggle="modal" data-bs-target="#criar" ng-click="novoContato()">
        <i class="fas fa-plus me-2"></i>
        Cadastrar novo
    </a>

    <div class="alert alert-sm alert-warning mt-2 mb-0" ng-show="!pessoa.contatos.length">
        Esta pessoa ainda não possui nenhum contato cadastrado!
    </div>

    <table class="table table-dark table-striped table-hover" ng-show="pessoa.contatos.length">
        <thead>
            <tr>
                <th>Contato</th>
                <th>Tipo</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="contato in pessoa.contatos">
                <td>
                    @{{ contato.contato }}
                </td>
                <td>
                    @{{ contato.tipo }}
                </td>
                <td>
                    <a href="" data-bs-toggle="modal" data-bs-target="#editar" ng-click="editarContato(contato)" class="btn btn-sm btn-primary ms-2">
                        <i class="fas fa-edit me-2"></i>
                        Editar
                    </a>
                    <a href="" ng-click="excluirContato(contato)" class="btn btn-sm btn-danger ms-2">
                        <i class="fas fa-trash-alt me-2"></i>
                        Excluir
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<!-- Modal Criar -->
<div class="modal fade" tabindex="-1" id="criar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cadastrar Contato</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="" class="form-label">Contato</label>
                    <input id="criar_nome" type="text" ng-enter="criarContato()" placeholder="Contato" class="form-control" ng-model="contatoCriar.contato">
                </div>
                <div class="form-group mt-3">
                    <label for="" class="form-label">Tipo</label>
                    <select ng-enter="criarContato()" class="form-select" ng-model="contatoCriar.tipo">
                        <option value="">Selecione...</option>
                        <option>Telefone</option>
                        <option>E-mail</option>
                        <option>WhatsApp</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" ng-click="criarContato()" class="btn btn-success">Salvar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Editar -->
<div class="modal fade" tabindex="-1" id="editar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Editar Contato</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="" class="form-label">Contato</label>
                    <input id="editar_nome" ng-enter="salvarContato()" type="text" placeholder="Contato" class="form-control" ng-model="contatoEditar.contato">
                </div>
                <div class="form-group mt-3">
                    <label for="" class="form-label">Tipo</label>
                    <select ng-enter="salvarContato()" class="form-select" ng-model="contatoEditar.tipo">
                        <option value="">Selecione...</option>
                        <option>Telefone</option>
                        <option>E-mail</option>
                        <option>WhatsApp</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" ng-click="salvarContato()" class="btn btn-success">Salvar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>